import '@/app/__styles__/index.css';
import '@mantine/core/styles.css';

import { WithProviders } from '@/app/__providers__';
import type { Metadata } from 'next';
import type { ReactNode } from 'react';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export const AuthLayout = ({ children }: Readonly<{ children: ReactNode }>) => (
	<html lang='ru'>
		<body>
			<WithProviders>{children}</WithProviders>
		</body>
	</html>
);
