import '@mantine/charts/styles.css';
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';
import 'mantine-react-table/styles.css';
import type { Metadata } from 'next';
import { type ReactNode } from 'react';
import './index.css';

import { Navbar } from '@/widgets/navbar';

import { WithProviders } from './__providers__';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
	return (
		<html lang='ru'>
			<body>
				<WithProviders>
					<Navbar>{children}</Navbar>
				</WithProviders>
			</body>
		</html>
	);
};
