import '@mantine/core/styles.css'
import './index.css'

import type { Metadata } from 'next'
import type { ReactNode } from 'react'

import { Navbar } from '@/widgets/navbar'

import { WithProviders } from './__providers__'

export const metadata: Metadata = { title: 'Create Next App', description: 'Generated by create next app' }

export const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => (
  <html lang='ru'>
    <body>
      <WithProviders>
        <Navbar>{children}</Navbar>
      </WithProviders>
    </body>
  </html>
)
